# Generated by Django 4.2.29 on 2026-03-06 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_mental_load_score', models.FloatField(default=0)),
                ('dominant_stressor', models.CharField(blank=True, max_length=100)),
                ('improvement_areas', models.TextField(blank=True)),
                ('positive_trends', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar_initial', models.CharField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_log_date', models.DateField(blank=True, null=True)),
                ('total_logs', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_hours', models.FloatField(default=0, help_text='Hours studied today')),
                ('break_count', models.IntegerField(default=0, help_text='Number of breaks taken')),
                ('avg_break_duration', models.IntegerField(default=0, help_text='Avg break duration in minutes')),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_pending', models.IntegerField(default=0)),
                ('deadline_stress', models.IntegerField(default=5, help_text='1-10 scale')),
                ('screen_time_hours', models.FloatField(default=0)),
                ('social_media_hours', models.FloatField(default=0)),
                ('productive_app_hours', models.FloatField(default=0)),
                ('entertainment_hours', models.FloatField(default=0)),
                ('sleep_hours', models.FloatField(default=7)),
                ('sleep_quality', models.IntegerField(default=5, help_text='1-10 scale')),
                ('bedtime_hour', models.IntegerField(default=23, help_text='Hour of bedtime (0-23)')),
                ('wake_time_hour', models.IntegerField(default=7, help_text='Hour of wake time (0-23)')),
                ('exercise_minutes', models.IntegerField(default=0)),
                ('exercise_type', models.CharField(blank=True, max_length=50)),
                ('steps_count', models.IntegerField(default=0)),
                ('physical_fatigue', models.IntegerField(default=5, help_text='1-10 scale')),
                ('social_interactions', models.IntegerField(default=0, help_text='Number of meaningful conversations')),
                ('family_time_minutes', models.IntegerField(default=0)),
                ('relationship_stress', models.IntegerField(default=3, help_text='1-10 scale')),
                ('social_satisfaction', models.IntegerField(default=5, help_text='1-10 scale')),
                ('conflict_count', models.IntegerField(default=0, help_text='Number of conflicts today')),
                ('extracurricular_hours', models.FloatField(default=0)),
                ('hobby_time_minutes', models.IntegerField(default=0)),
                ('club_activities', models.BooleanField(default=False)),
                ('mood_score', models.IntegerField(default=5, help_text='1-10 scale (1=terrible, 10=amazing)')),
                ('anxiety_level', models.IntegerField(default=3, help_text='1-10 scale')),
                ('focus_level', models.IntegerField(default=5, help_text='1-10 scale')),
                ('motivation_level', models.IntegerField(default=5, help_text='1-10 scale')),
                ('overthinking_episodes', models.IntegerField(default=0)),
                ('avg_typing_speed', models.IntegerField(default=0, help_text='WPM average')),
                ('typo_frequency', models.IntegerField(default=0, help_text='Typos per 100 words')),
                ('notification_count', models.IntegerField(default=0)),
                ('phone_pickups', models.IntegerField(default=0)),
                ('journal_entry', models.TextField(blank=True)),
                ('stressors', models.TextField(blank=True, help_text="What's stressing you out?")),
                ('predicted_mental_load', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('mental_load_score', models.FloatField(blank=True, help_text='0-100 score', null=True)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
